baseurl = "https://hungry-visvesvaraya-d246d6.netlify.com/"
title = "Hugo Theme"
author = "@JeffProd"
copyright = "Copyright © 2008–2018, @JeffProd"
canonifyurls = true
paginate = 3

theme = "hugo-blog-jeffprod"

[taxonomies]
    tag = "tags"
    archive = "archives"
