baseurl = "https://hungry-visvesvaraya-d246d6.netlify.com/"
title = "Hugo Theme"
author = "@Kev"
copyright = "Copyright © Kev"
canonifyurls = true
paginate = 3
disqus="blog-kev"

theme = "hugo-blog-jeffprod"

[taxonomies]
    tag = "tags"
    archive = "archives"
