baseurl = "https://hungry-visvesvaraya-d246d6.netlify.com/"
title = "Kevinlpd security blog"
author = "@Kev"
copyright = "Copyright © Kev"
canonifyurls = true
paginate = 10

theme = "hugo-blog-jeffprod"

[taxonomies]
    tag = "tags"
    archive = "archives"
	category = "categories"
[params]
	description = "_Winter is comming_"
	twitter = "kvin_lpd"
	github = "kevin-ksis"

