baseurl = "https://hungry-visvesvaraya-d246d6.netlify.com/"
title = "Kevinlpd security blog"
author = "@Kev"
copyright = "Copyright © Kev"
canonifyurls = true
paginate = 3

theme = "hugo-blog-jeffprod"

[taxonomies]
    tag = "tags"
    archive = "archives"
